<?php

/**
 * Implementation of hook_sassy_resolve_path_NAMESPACE().
 */
function sassy_bootstrap_sassy_resolve_path_bootstrap($filename, $syntax = 'scss') {
  $path = drupal_get_path('module', 'sassy_bootstrap') . '/bootstrap/lib/';
  $filename = str_replace(array('.scss', '.sass'), '', trim($filename, ' /._'));
  switch ($filename) {
    case '*':
    case 'bootstrap':
      return $path . 'bootstrap.scss';
    case 'forms':
    case 'mixins':
    case 'patterns':
    case 'reset':
    case 'scaffolding':
    case 'tables':
    case 'variables':
      return $path . $filename . '.scss';
  }
  drupal_set_message(t('Unrecognised stylesheet "@file" requested. Available files are: bootstrap, forms, mixins, patterns, reset, scaffolding, tables, variables.', array('@file' => $filename)), 'error');
  return FALSE;
}

/**
 * Implementation of hook_library().
 */
function sassy_bootstrap_library() {
  $path = drupal_get_path('module', 'sassy_bootstrap');
  $return = array();
  $all = array();
  foreach (array('alerts', 'dropdown', 'modal', 'popover', 'scrollspy', 'tabs', 'twipsy') as $library) {
    $return['bootstrap-' . $library] = array(
      'title' => 'Bootstrap ' . ucwords($library),
      'website' => 'http://twitter.github.com/bootstrap/javascript.html#' . $library,
      'version' => '1.3.0',
      'js' => array($path . '/bootstrap/js/bootstrap-' . $library . '.js'),
      'css' => array($path . '/bootstrap/lib/patterns.scss'),
    );
    $all[$library] = $path . '/bootstrap/js/bootstrap-' . $library . '.js';
  }
  $return['bootstrap'] = array(
    'title' => 'Bootstrap complete',
    'website' => 'http://twitter.github.com/bootstrap/',
    'version' => '1.3.0',
    'js' => $all,
    'css' => array($path . '/boostrap/lib/bootstrap.scss'),
  );
  return $return;
}