<?php

/**
 * Implementation hook_sassy_resolve_path_NAMESPACE().
 */
function sassy_foundation_sassy_resolve_path_foundation($filename, $syntax = 'scss') {
  $path = drupal_get_path('module', 'sassy_foundation') . '/foundation/stylesheets/';
  $filename = str_replace(array('.scss', '.sass', '.css'), '', trim($filename, ' /._'));
  if ($filename == '*') {
    $filename == 'foundation';
  }
  if (in_array($filename, array('foundation', 'app', 'forms', 'globals', 'grid', 'ie', 'mobile', 'orbit', 'reveal', 'typography', 'ui'))) {
    return $path . $filename . '.css';
  }
  drupal_set_message(t('Unrecognised stylesheet "@file" requested. Available files are: @list', array('@list' => implode(', ', $available), '@file' => $filename)), 'error');
  return FALSE;
}

/**
 * Implementation of hook_library().
 */
function sassy_foundation_library() {
  $path = drupal_get_path('module', 'sassy_foundation') . '/foundation/';
  return array(
    'foundation-orbit' => array(
      'title' => 'Foundation Orbit',
      'version' => '1.3.0',
      'website' => 'http://foundation.zurb.com/docs/orbit.php',
      'js' => array($path . 'javascripts/jquery.orbit-1.3.0.js'),
      'css' => array($path . 'stylesheets/orbit.css'),
    ),
    'foundation-reveal' => array(
      'title' => 'Foundation Reveal',
      'version' => '2.0.3',
      'website' => 'http://foundation.zurb.com/docs/reveal.php',
      'js' => array($path . 'javascripts/jquery.reveal.js'),
      'css' => array($path . 'stylesheets/reveal.css'),
    ),
  );
}